apt-get install -y  sudo \
                    git \
                    python3 \
                    python3-setuptools \
                    python3-pip \
                    python3-dev \
                    python3-venv \
                    python3-wheel \
                    xvfb \
                    xserver-xephyr \
                    libxml2-dev \
                    libxslt-dev \
                    postgresql-server-dev-all \
                    libcurl4-openssl-dev \
                    proxychains \
                    unzip \
                    build-essential \
                    libssl-dev \
                    libz-dev \
                    libffi-dev \
                    postgresql \
                    postgresql-client \
                    postgresql-client-common \
